spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant_dev?useSSL=false&allowPublicKeyRetrieval=true
    username: admin_dev
    password: admin_dev
    driver-class-name: com.mysql.cj.jdbc.Driver