spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant_prod?useSSL=false&allowPublicKeyRetrieval=true
    username: admin_prod
    password: admin_prod
    driver-class-name: com.mysql.cj.jdbc.Driver