spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant_local?useSSL=false&allowPublicKeyRetrieval=true
    username: admin_local
    password: admin_local
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

# Desative o Flyway se estiver usando (para evitar conflitos)
flyway:
  enabled: false