spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant_qa?useSSL=false&allowPublicKeyRetrieval=true
    username: admin_qa
    password: admin_qa
    driver-class-name: com.mysql.cj.jdbc.Driver