# k8s/mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root_password: cm9vdA==            # base64 for 'root'
  user_password: YWRtaW5fbG9jYWw=    # base64 for 'admin_local'